[package]
name = "vidtoolkit-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.20", features = ["cargo", "derive"] }
indicatif = "0.17.8"
rayon = "1.10"
